---
- hosts: all
  remote_user: sanyi
  tasks:

  - name: ssh key feltöltése
    authorized_key:
      user: sanyi
      state: present
      manage_dir: yes
      key: https://github.com/ivansandor97.keys


  - name:  Legyen sudo csoport
    group:
      name: sudo
      state: present

  - name: A sudo csoport felhasználói jelszó nélkül használhatják a sudo-t.
    template:
      src: 95-sudo-group.j2
      dest: /etc/sudoers.d/95-sudo-group
      mode: 0440
